POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Tiago",
    "email": "tiago@email.coma",
    "password": "123456"
}

###

POST http://localhost:3003/movie
Content-Type: application/json

{
    "title": "Titanic",
    "description": "A huge ship that sinks.",
    "durationInMinutes": 184,
    "yearOfRelease": 1997
}
